#-------------------------------------------------------------------------
#
# Makefile for src/pl/plmdb (MollyDB's SQL procedural language)
#
# Copyright (c) 1994, Regents of the University of California
#
# src/pl/plmdb/Makefile
#
#-------------------------------------------------------------------------

subdir = src/pl/plmdb
top_builddir = ../../..
include $(top_builddir)/src/Makefile.global

SUBDIRS = src

$(recurse)
